### ISSUE TITLE
How to get optimal parameters for models? 

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#1036]
## ❓ Questions and Help
Qlib comes with some benchmarks models, such as XGBoost, examples for china stock market. And such models already come with some predefined parameters that, if I understood correctly, are optimal paramters.

However, if I modify the china dataset or use another dataset from a different stock market such as US or BR(Brazilian) how can I get such optimal parameters as the ones shown below removed from `workflow_config_xgboost_Alpha360.yaml` ?

```
model:
        class: XGBModel
        module_path: qlib.contrib.model.xgboost
        kwargs:
            eval_metric: rmse
            colsample_bytree: 0.8879
            eta: 0.0421
            max_depth: 8
            n_estimators: 647
            subsample: 0.8789
            nthread: 20
```
