### ISSUE TITLE
How to add custom features in Alpha158? 如何在Alpha158中加入其它自定义的特征？

### ISSUE THREAD

**Issue by SmilingJimmy** [microsoft/qlib#1083]
### Question 1

Hi! `Qlib` has already built some excellent datasets (including `Alpha158` & `Alpha360`) with satisfying training & backtesting results. However, I am still wondering whether some **custom features** could be appended besides `Alpha158` or not. Those custom features may include some features related to financial reports, and other technical features that haven't been involved in  `Alpha158` yet. If so, how can I achieve this in codes?

您好！`Qlib`已经建立了一些优秀的数据集（包括`Alpha158`和`Alpha360`），它们具有令人满意的训练和回测结果。不过，我还想知道，基于`Alpha158`的数据集，是否还可以添加一些**自定义特征**。这些自定义特征可能会包括一些与公司财务报告相关的特征，以及尚未纳入`Alpha158`的其他技术指标。如果可以的话，应当如何在代码中实现这一点？

### Question 2

I also have another question related to `Alpha158`. I notice that there are **2 types of pre-processing approaches** towards `Alpha158`: one in [workflow_config_mlp_Alpha158.yaml](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/MLP/workflow_config_mlp_Alpha158.yaml), the other in [workflow_config_gru_Alpha158.yaml](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/GRU/workflow_config_gru_Alpha158.yaml).

我还有一个关于`Alpha158`的问题。我注意到有**2种预处理**`Alpha158`的方式：一种在[workflow_config_mlp_Alpha158.yaml](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/MLP/workflow_config_mlp_Alpha158.yaml)中，而另一种在[workflow_config_gru_Alpha158.yaml](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/GRU/workflow_config_gru_Alpha158.yaml)中。

The former drops a column `VWAP0`, fills `NaN` with `CSZFillna`, and then normalizes the dataset with `CSZScoreNorm`.

前者删去了`VWAP0`列，使用横截面均值——`CSZFillna`的方式补缺，并使用横截面Z分数`CSZScoreNorm`标准化。

```
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market
    infer_processors: [
        {
            "class" : "DropCol", 
            "kwargs":{"col_list": ["VWAP0"]}
        },
        {
             "class" : "CSZFillna", 
             "kwargs":{"fields_group": "feature"}
        }
    ]
    learn_processors: [
        {
            "class" : "DropCol", 
            "kwargs":{"col_list": ["VWAP0"]}
        },
        {
            "class" : "DropnaProcessor", 
            "kwargs":{"fields_group": "feature"}
        },
        "DropnaLabel",
        {
            "class": "CSZScoreNorm", 
            "kwargs": {"fields_group": "label"}
        }
    ]
    process_type: "independent"
```

The latter chooses 20 columns, fills `NaN` with `Fillna`, and then normalizes the dataset with `RobustZScoreNorm` & `CSRankNorm`.

后者选择了20列，使用0——`Fillna`的方式补缺，并使用稳健Z分数`RobustZScoreNorm`和横截面排序百分数`CSRankNorm`标准化。

```
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", 
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", 
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"] 
```

So, what are the reasons for using 2 different types of pre-processing approaches towards `Alpha158`? Are the pre-processing approaches related to **models** (the former for `MLP` while the latter for `RNN`)?

那么，对`Alpha158`数据集使用2种预处理方式的原因是什么？预处理方式是否与**模型**相关（前者用于`MLP`，而后者用于`RNN`）？

Thanks in advance!

谢谢！
