### ISSUE TITLE
配置好 qlib-server服务器,使用 Mac 系统出现 NFS不能正常挂载的故障

### ISSUE THREAD

**Issue by markthink** [microsoft/qlib#1450]
## To Reproduce

1. 在Mac 系统无法正常完成 NFS 数据挂载

配置文件:
```yaml
calendar_provider:
    class: LocalCalendarProvider
    kwargs:
        remote: True
feature_provider:
    class: LocalFeatureProvider
    kwargs:
        remote: True
expression_provider: LocalExpressionProvider
instrument_provider: ClientInstrumentProvider
dataset_provider: ClientDatasetProvider
provider: ClientProvider
expression_cache: null
dataset_cache: null
calendar_cache: null

provider_uri: 10.71.117.61:/
mount_path: ./cn_data/
auto_mount: True
flask_server: 10.71.117.61
flask_port: 9710
```

客户端配置:
```python
import qlib
from qlib.data import D

qlib.init_from_yaml_conf('./config.yaml')
fox = D.calendar(start_time='2010-01-01', end_time='2017-12-31', freq='day')[:2]
print(fox)
```

## Expected Behavior

生成的命令如下: 在 Mac 环境此命令出现未预期的行为
sudo mount.nfs 10.71.117.61:/ cn_data:\\'

## Screenshot

将 win 改成 windows 问题得以解决
![image](https://user-images.githubusercontent.com/1718716/221170580-135b1b57-b4b9-4d23-ac25-d42b0c69ee05.png)

## Environment

 - Qlib version:  '0.9.1.99'
 - Python version: Python 3.10.9
 - OS (`Windows`, `Linux`, `MacOS`):  Mac OS
 - Commit number (optional, please provide it if you are using the dev version):
 - 
```python
# qlib/config.py : 342 line 
if "win" in platform.system().lower():

fix:
if "windows" in platform.system().lower():
```
