### ISSUE TITLE
Is there a way to export trading decisions?

### ISSUE THREAD

**Issue by guoz14** [microsoft/qlib#1692]
Hi all, I am just curious that if there exists a function already that could yield something like two lists which include current trading decisions for stocks.

**Comment by ElonJustin7** [comment]
回测框架里的positions_normal可以显示每一天的持仓情况和占比

**Comment by guoz14** [comment]
> 回测框架里的positions_normal可以显示每一天的持仓情况和占比

好的，感谢！

**Comment by Imbernoulli** [comment]
You can also refer to #1655, where we discussed more detailed. In sort, change the yaml to this:
```
---
qlib_init:
  ...
task:
  model:
    ...
  dataset:
    ...
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ...
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config:
          executor:
            class: SimulatorExecutor
            module_path: qlib.backtest.executor
            kwargs:
              time_per_step: day
              generate_portfolio_metrics: True
              verbose: True
          strategy:
            ...
          backtest:
            ...
```

I add `executor: class: SimulatorExecutor module_path: qlib.backtest.executor kwargs: time_per_step: day generate_portfolio_metrics: True verbose: True`
to `port_analysis_config: &port_analysis_config` and it works.
