### ISSUE TITLE
FileExistsError: label.pkl

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#172]
ERROR - qlib.workflow - [utils.py:35] - An exception has been raised[FileExistsError: label.pkl].

xx/qlib/workflow/record_temp.py", line 106, in check
    raise FileExistsError(item)
FileExistsError: label.pkl

**Comment by you-n-g** [comment]
@pan-cai  Can you provide more details to reproduce this issue? 
Thanks

**Comment by pan-cai** [comment]
> @pan-cai Can you provide more details to reproduce this issue?
> Thanks

I changed yaml file, 
```
    dataset:
        class: DatasetHQuant
        module_path: qlib.quant.dataset_quant
        #class: DatasetH
        #module_path: qlib.data.dataset
```
DatasetHQuant is the same with DatasetH

**Comment by pan-cai** [comment]
workflow_config_lightgbm_Alpha9159.yaml

```
qlib_init:
    provider_uri: "xx/qlib_data/cn_data"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.quant.strategy_quant
        kwargs:
            topk: 50
            n_drop: 5
    backtest:
        verbose: False
        limit_threshold: 0.095
        account: 100000000
        benchmark: *benchmark
        deal_price: close
        open_cost: 0.0005
        close_cost: 0.0015
        min_cost: 5
task:
    model:
        class: LGBModel
        module_path: qlib.quant.model_quant
        kwargs:
            loss: mse
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 205.6999
            lambda_l2: 580.9768
            max_depth: 8
            num_leaves: 210
            num_threads: 20
    dataset:
        #class: DatasetHQuant
        #module_path: qlib.quant.dataset_quant
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha9001
                module_path: qlib.quant.handler_quant
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2014-12-31]
                valid: [2015-01-01, 2016-12-31]
                test: [2017-01-01, 2020-08-01]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: {}
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
```
