### ISSUE TITLE
Any examples to use Filter?

### ISSUE THREAD

**Issue by bamboowind** [microsoft/qlib#230]
## 📖 Documentation

https://qlib.readthedocs.io/en/latest/reference/api.html#module-qlib.data.filter
From this part of the document, seems Filter is quite powerful, but no idea how to use it in the workflow. Can you give out some sample in .yml or in code?

**Comment by you-n-g** [comment]
We merged a PR for this feature fseveral days ago.
https://github.com/microsoft/qlib/pull/220

@Derek-Wds  will give more documents about using filter in  workflow later.
Thanks

**Comment by Derek-Wds** [comment]
@bamboowind Here is an example code that you can refer to for now (thanks for @shijie2016 providing the scripts~ [#218 ](https://github.com/microsoft/qlib/issues/218)):

```
filter: &filter
    filter_type: ExpressionDFilter
    rule_expression: "Ref($close, -2) / Ref($close, -1) > 1"
    filter_start_time: 2010-01-01
    filter_end_time: 2010-01-07
    keep: False

data_handler_config: &data_handler_config
    start_time: 2010-01-01
    end_time: 2021-01-22
    fit_start_time: 2010-01-01
    fit_end_time: 2015-12-31
    instruments:
        market: *market
        filter_pipe: [*filter]
```
Hope it helps!
